/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload */
        post: operations["upload_api_v1_assets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Asset */
        get: operations["asset_api_v1_assets__id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets/{id}/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Asset File */
        get: operations["asset_file_api_v1_assets__id___kind__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets/{id}/extractions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Extract Asset */
        post: operations["extract_asset_api_v1_assets__id__extractions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stickers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sticker */
        post: operations["sticker_api_v1_stickers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stickers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Sticker */
        get: operations["get_sticker_api_v1_stickers__id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Edit Sticker */
        patch: operations["edit_sticker_api_v1_stickers__id__patch"];
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Projects */
        get: operations["projects_api_v1_projects_get"];
        put?: never;
        /** Project */
        post: operations["project_api_v1_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_api_v1_projects__id__get"];
        put?: never;
        post?: never;
        /** Delete Project */
        delete: operations["delete_project_api_v1_projects__id__delete"];
        options?: never;
        head?: never;
        /** Edit Project */
        patch: operations["edit_project_api_v1_projects__id__patch"];
        trace?: never;
    };
    "/api/v1/projects/{id}/restore-source-layout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore Source Layout */
        post: operations["restore_source_layout_api_v1_projects__id__restore_source_layout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/photo-projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Photo Project */
        post: operations["photo_project_api_v1_photo_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/photo-projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Photo Project */
        get: operations["get_photo_project_api_v1_photo_projects__id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Edit Photo Project */
        patch: operations["edit_photo_project_api_v1_photo_projects__id__patch"];
        trace?: never;
    };
    "/api/v1/photo-projects/{id}/draft-preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Photo Draft Preview */
        post: operations["photo_draft_preview_api_v1_photo_projects__id__draft_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/photo-projects/{id}/renders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Photo Render */
        post: operations["photo_render_api_v1_photo_projects__id__renders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{id}/cut-policy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Project Cut Policy */
        post: operations["project_cut_policy_api_v1_projects__id__cut_policy_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{id}/geometry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Geometry */
        get: operations["geometry_api_v1_projects__id__geometry_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{id}/layouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Layout */
        post: operations["layout_api_v1_projects__id__layouts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{id}/renders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Render */
        post: operations["render_api_v1_projects__id__renders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/operations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Operation */
        get: operations["operation_api_v1_operations__id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/renders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Render */
        get: operations["get_render_api_v1_renders__id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/renders/{id}/artifacts/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Render Artifact */
        get: operations["render_artifact_api_v1_renders__id__artifacts__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/printers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Printers */
        get: operations["printers_api_v1_printers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/printers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Printer */
        get: operations["printer_api_v1_printers__id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** History */
        get: operations["history_api_v1_jobs_get"];
        put?: never;
        /** Submit */
        post: operations["submit_api_v1_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job */
        get: operations["job_api_v1_jobs__id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{id}/sheets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sheets */
        get: operations["sheets_api_v1_jobs__id__sheets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job Events */
        get: operations["job_events_api_v1_jobs__id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel */
        post: operations["cancel_api_v1_jobs__id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume */
        post: operations["resume_api_v1_jobs__id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{id}/reprints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reprint */
        post: operations["reprint_api_v1_jobs__id__reprints_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{id}/resolutions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolution */
        post: operations["resolution_api_v1_jobs__id__resolutions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Event Stream */
        get: operations["event_stream_api_v1_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_api_v1_assets_post */
        Body_upload_api_v1_assets_post: {
            /** File */
            file: string;
        };
        /** CutGeometry */
        CutGeometry: {
            /**
             * Schema Version
             * @constant
             */
            schema_version: "1.0";
            /** Geometry Engine */
            geometry_engine: string;
            provenance: components["schemas"]["GeometryProvenance"];
            /** Page Id */
            page_id: string;
            /** Page Mm */
            page_mm: [
                number,
                number
            ];
            /**
             * Units
             * @constant
             */
            units: "mm";
            /**
             * Coordinate Space
             * @constant
             */
            coordinate_space: "sheet_design";
            /**
             * Origin
             * @constant
             */
            origin: "top_left";
            /**
             * X Direction
             * @constant
             */
            x_direction: "right";
            /**
             * Y Direction
             * @constant
             */
            y_direction: "down";
            /**
             * Geometry Stage
             * @constant
             */
            geometry_stage: "finished_cut_pre_device";
            /** Shapes */
            shapes: components["schemas"]["CutShape"][];
        };
        /** CutPolicy */
        CutPolicy: {
            /**
             * Cut Padding Mm
             * @default 0
             */
            cut_padding_mm: number;
            /**
             * Minimum Cut Width Mm
             * @default 0
             */
            minimum_cut_width_mm: number;
        };
        /** CutShape */
        CutShape: {
            /** Id */
            id: string;
            /** Sticker Id */
            sticker_id: string;
            /** Sticker Revision */
            sticker_revision: number;
            /** Placement Id */
            placement_id: string;
            outer: components["schemas"]["Ring"];
            /** Holes */
            holes: components["schemas"]["Ring"][];
            cut_policy?: components["schemas"]["CutPolicy"];
        };
        /** ExtractionInput */
        ExtractionInput: {
            /** Name */
            name: string;
        };
        /** GeometryProvenance */
        GeometryProvenance: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "draft" | "render";
            /** Project Id */
            project_id: string;
            /** Project Revision */
            project_revision: number;
            /** Render Id */
            render_id: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobInput */
        JobInput: {
            /** Render Id */
            render_id: string;
            /**
             * Printer Id
             * @default simulator
             * @enum {string}
             */
            printer_id: "simulator" | "pixcut-s1-usb";
            /**
             * Mode
             * @default print_cut
             * @enum {string}
             */
            mode: "print_cut" | "print_only";
            /** Pages */
            pages: number[];
            /**
             * Copies
             * @default 1
             */
            copies: number;
            /**
             * Accepted Profile Id
             * @enum {string}
             */
            accepted_profile_id: "simulator-v1" | "sticker-4x7-jpeg" | "photo-4x6-jpeg";
            /**
             * Confirmed
             * @constant
             */
            confirmed: true;
            /** Confirmed Media */
            confirmed_media?: "4x6 photo paper" | null;
            /** Idempotency Key */
            idempotency_key: string;
            /**
             * Name
             * @default Sticker sheet
             */
            name: string;
        };
        /** LayoutInput */
        LayoutInput: {
            /** Revision */
            revision: number;
            /** Sticker Id */
            sticker_id: string;
            /**
             * Mode
             * @default fill
             * @enum {string}
             */
            mode: "fill" | "grid" | "quantity";
            /**
             * Width Mm
             * @default 25
             */
            width_mm: number;
            /**
             * Height Mm
             * @default 25
             */
            height_mm: number;
            /**
             * Gap Mm
             * @default 2
             */
            gap_mm: number;
            /**
             * Margin Mm
             * @default 5
             */
            margin_mm: number;
            /** Quantity */
            quantity?: number | null;
            /** Rows */
            rows?: number | null;
            /** Columns */
            columns?: number | null;
        };
        /** Page */
        Page: {
            /** Id */
            id: string;
            /** Placements */
            placements: components["schemas"]["Placement"][];
            /**
             * Source Layout
             * @default false
             */
            source_layout: boolean;
        };
        /** PhotoAdjustments */
        PhotoAdjustments: {
            /**
             * Exposure
             * @default 0
             */
            exposure: number;
            /**
             * Contrast
             * @default 0
             */
            contrast: number;
            /**
             * Highlights
             * @default 0
             */
            highlights: number;
            /**
             * Shadows
             * @default 0
             */
            shadows: number;
            /**
             * Temperature
             * @default 0
             */
            temperature: number;
            /**
             * Tint
             * @default 0
             */
            tint: number;
            /**
             * Saturation
             * @default 0
             */
            saturation: number;
            /**
             * Sharpening
             * @default 0
             */
            sharpening: number;
            /**
             * Grain
             * @default 0
             */
            grain: number;
        };
        /** PhotoCrop */
        PhotoCrop: {
            /**
             * X
             * @default 0
             */
            x: number;
            /**
             * Y
             * @default 0
             */
            y: number;
            /**
             * Width
             * @default 1
             */
            width: number;
            /**
             * Height
             * @default 1
             */
            height: number;
        };
        /** PhotoProjectEdit */
        PhotoProjectEdit: {
            crop?: components["schemas"]["PhotoCrop"];
            /**
             * Layout
             * @default single
             * @enum {string}
             */
            layout: "single" | "yearbook_2x3" | "yearbook_1_5x2" | "photobooth_2x6";
            /**
             * Orientation
             * @default auto
             * @enum {string}
             */
            orientation: "auto" | "portrait" | "landscape";
            /**
             * Framing
             * @default fill
             * @enum {string}
             */
            framing: "fill" | "contain";
            /**
             * Preset
             * @default original
             * @enum {string}
             */
            preset: "original" | "auto_balance" | "vivid" | "warm" | "cool" | "black_and_white";
            /**
             * Film Look
             * @default none
             * @enum {string}
             */
            film_look: "none" | "warm_negative" | "faded_print" | "vivid_slide" | "cool_chrome";
            /**
             * Print Quality
             * @default 95
             */
            print_quality: number;
            adjustments?: components["schemas"]["PhotoAdjustments"];
            /** Name */
            name: string;
            /** Asset Id */
            asset_id: string;
            /** Expected Revision */
            expected_revision: number;
        };
        /** PhotoProjectInput */
        PhotoProjectInput: {
            crop?: components["schemas"]["PhotoCrop"];
            /**
             * Layout
             * @default single
             * @enum {string}
             */
            layout: "single" | "yearbook_2x3" | "yearbook_1_5x2" | "photobooth_2x6";
            /**
             * Orientation
             * @default auto
             * @enum {string}
             */
            orientation: "auto" | "portrait" | "landscape";
            /**
             * Framing
             * @default fill
             * @enum {string}
             */
            framing: "fill" | "contain";
            /**
             * Preset
             * @default original
             * @enum {string}
             */
            preset: "original" | "auto_balance" | "vivid" | "warm" | "cool" | "black_and_white";
            /**
             * Film Look
             * @default none
             * @enum {string}
             */
            film_look: "none" | "warm_negative" | "faded_print" | "vivid_slide" | "cool_chrome";
            /**
             * Print Quality
             * @default 95
             */
            print_quality: number;
            adjustments?: components["schemas"]["PhotoAdjustments"];
            /** Name */
            name: string;
            /** Asset Id */
            asset_id: string;
        };
        /** PhotoRenderInput */
        PhotoRenderInput: {
            /** Revision */
            revision: number;
        };
        /** PhotoSettings */
        PhotoSettings: {
            crop?: components["schemas"]["PhotoCrop"];
            /**
             * Layout
             * @default single
             * @enum {string}
             */
            layout: "single" | "yearbook_2x3" | "yearbook_1_5x2" | "photobooth_2x6";
            /**
             * Orientation
             * @default auto
             * @enum {string}
             */
            orientation: "auto" | "portrait" | "landscape";
            /**
             * Framing
             * @default fill
             * @enum {string}
             */
            framing: "fill" | "contain";
            /**
             * Preset
             * @default original
             * @enum {string}
             */
            preset: "original" | "auto_balance" | "vivid" | "warm" | "cool" | "black_and_white";
            /**
             * Film Look
             * @default none
             * @enum {string}
             */
            film_look: "none" | "warm_negative" | "faded_print" | "vivid_slide" | "cool_chrome";
            /**
             * Print Quality
             * @default 95
             */
            print_quality: number;
            adjustments?: components["schemas"]["PhotoAdjustments"];
        };
        /** Placement */
        Placement: {
            /** Id */
            id: string;
            /** Sticker Id */
            sticker_id: string;
            /** X Mm */
            x_mm: number;
            /** Y Mm */
            y_mm: number;
            /** Width Mm */
            width_mm: number;
            /** Height Mm */
            height_mm: number;
            /**
             * Rotation
             * @default 0
             * @enum {integer}
             */
            rotation: 0 | 90;
            /**
             * Pinned
             * @default false
             */
            pinned: boolean;
        };
        /** PrinterInfo */
        PrinterInfo: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Found */
            found: boolean;
            /** Ready */
            ready: boolean;
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "device_missing" | "worker_offline" | "attention";
            worker: components["schemas"]["WorkerStatus"];
            /** Attention Job Id */
            attention_job_id: string | null;
            /**
             * Execution Mode
             * @enum {string}
             */
            execution_mode: "hardware" | "simulator";
            /** Profile */
            profile: {
                [key: string]: unknown;
            };
            /** Profiles */
            profiles: {
                [key: string]: unknown;
            }[];
            /** Hardware Validated */
            hardware_validated: boolean;
        };
        /** ProjectCutPolicyInput */
        ProjectCutPolicyInput: {
            /** Expected Revision */
            expected_revision: number;
            /**
             * Cut Padding Mm
             * @default 0
             */
            cut_padding_mm: number;
            /**
             * Minimum Cut Width Mm
             * @default 0
             */
            minimum_cut_width_mm: number;
            /**
             * Fit Extracted Sheet
             * @default true
             */
            fit_extracted_sheet: boolean;
        };
        /** ProjectEdit */
        ProjectEdit: {
            /**
             * Kind
             * @default sticker
             * @constant
             */
            kind: "sticker";
            /** Name */
            name: string;
            /** Bindings */
            bindings: {
                [key: string]: number;
            };
            /** Pages */
            pages?: components["schemas"]["Page"][];
            /** Expected Revision */
            expected_revision: number;
        };
        /** ProjectInput */
        ProjectInput: {
            /**
             * Kind
             * @default sticker
             * @constant
             */
            kind: "sticker";
            /** Name */
            name: string;
            /** Bindings */
            bindings: {
                [key: string]: number;
            };
            /** Pages */
            pages?: components["schemas"]["Page"][];
        };
        /** RenderInput */
        RenderInput: {
            /** Revision */
            revision: number;
            /**
             * Profile Id
             * @default simulator-v1
             * @constant
             */
            profile_id: "simulator-v1";
            /**
             * Lossless Required
             * @default true
             * @constant
             */
            lossless_required: true;
            /**
             * Image Format
             * @default auto_lossless
             * @enum {string}
             */
            image_format: "auto_lossless" | "png";
        };
        /** ReprintInput */
        ReprintInput: {
            /** Sheet Ids */
            sheet_ids: string[];
            /**
             * Copies
             * @default 1
             */
            copies: number;
            /**
             * Confirmed
             * @constant
             */
            confirmed: true;
            /**
             * Accepted Profile Id
             * @constant
             */
            accepted_profile_id: "simulator-v1";
            /** Idempotency Key */
            idempotency_key: string;
        };
        /** ResolutionInput */
        ResolutionInput: {
            /** Sheet Id */
            sheet_id: string;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "completed" | "failed" | "uncertain";
            /** Note */
            note: string;
            /** Expected Event Id */
            expected_event_id: number;
            /**
             * Printer Restarted
             * @default false
             */
            printer_restarted: boolean;
        };
        /** RestoreSourceLayoutInput */
        RestoreSourceLayoutInput: {
            /** Expected Revision */
            expected_revision: number;
        };
        /** Ring */
        Ring: {
            /**
             * Closed
             * @constant
             */
            closed: true;
            /** Points */
            points: [
                number,
                number
            ][];
        };
        /** StickerEdit */
        StickerEdit: {
            /** Name */
            name: string;
            /** Asset Id */
            asset_id: string;
            /** Outline */
            outline?: [
                number,
                number
            ][];
            /**
             * Cut Padding Mm
             * @default 0
             */
            cut_padding_mm: number;
            /**
             * Minimum Cut Width Mm
             * @default 0
             */
            minimum_cut_width_mm: number;
            /** Expected Revision */
            expected_revision: number;
        };
        /** StickerInput */
        StickerInput: {
            /** Name */
            name: string;
            /** Asset Id */
            asset_id: string;
            /** Outline */
            outline?: [
                number,
                number
            ][];
            /**
             * Cut Padding Mm
             * @default 0
             */
            cut_padding_mm: number;
            /**
             * Minimum Cut Width Mm
             * @default 0
             */
            minimum_cut_width_mm: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WorkerStatus */
        WorkerStatus: {
            /**
             * State
             * @enum {string}
             */
            state: "starting" | "idle" | "working" | "blocked" | "stopped" | "offline";
            /** Last Seen At */
            last_seen_at: string | null;
            /** Current Job Id */
            current_job_id: string | null;
            /** Message */
            message: string | null;
            /** Fresh */
            fresh: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    upload_api_v1_assets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_api_v1_assets_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    asset_api_v1_assets__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    asset_file_api_v1_assets__id___kind__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                kind: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extract_asset_api_v1_assets__id__extractions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExtractionInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sticker_api_v1_stickers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StickerInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sticker_api_v1_stickers__id__get: {
        parameters: {
            query?: {
                revision?: number | null;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_sticker_api_v1_stickers__id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StickerEdit"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    projects_api_v1_projects_get: {
        parameters: {
            query?: {
                kind?: ("photo" | "sticker") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    project_api_v1_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_api_v1_projects__id__get: {
        parameters: {
            query?: {
                revision?: number | null;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_project_api_v1_projects__id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_project_api_v1_projects__id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectEdit"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_source_layout_api_v1_projects__id__restore_source_layout_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RestoreSourceLayoutInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    photo_project_api_v1_photo_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PhotoProjectInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_photo_project_api_v1_photo_projects__id__get: {
        parameters: {
            query?: {
                revision?: number | null;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_photo_project_api_v1_photo_projects__id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PhotoProjectEdit"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    photo_draft_preview_api_v1_photo_projects__id__draft_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PhotoSettings"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    photo_render_api_v1_photo_projects__id__renders_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PhotoRenderInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    project_cut_policy_api_v1_projects__id__cut_policy_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCutPolicyInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    geometry_api_v1_projects__id__geometry_get: {
        parameters: {
            query?: {
                revision?: number | null;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CutGeometry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    layout_api_v1_projects__id__layouts_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LayoutInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    render_api_v1_projects__id__renders_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenderInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    operation_api_v1_operations__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_render_api_v1_renders__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    render_artifact_api_v1_renders__id__artifacts__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    printers_api_v1_printers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrinterInfo"][];
                };
            };
        };
    };
    printer_api_v1_printers__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrinterInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    history_api_v1_jobs_get: {
        parameters: {
            query?: {
                before?: string | null;
                limit?: number;
                state?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_api_v1_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_api_v1_jobs__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sheets_api_v1_jobs__id__sheets_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_events_api_v1_jobs__id__events_get: {
        parameters: {
            query?: {
                after?: number;
                limit?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_api_v1_jobs__id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_api_v1_jobs__id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reprint_api_v1_jobs__id__reprints_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReprintInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolution_api_v1_jobs__id__resolutions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolutionInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    event_stream_api_v1_events_get: {
        parameters: {
            query?: {
                after?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
